FROM ubuntu:latest
LABEL authors="svemar"
#zadny docker file, proste to tam presun a pust
# scp -r IdeaProjects/softiq/src/* root@css-sro.cz:/var/www/softiq/public_html
# nebo
# scp -r IdeaProjects/softiq/src/* root@css-sro.cz:/var/www/softiq-reality/public_html

# uz ne takhle, uz to jeda pres pache
#tenhle podporuje php
# docker run -d -p 8082:80 --name softiq1.0php -v /var/www/softiq:/var/www/html php:apache