FROM ubuntu:latest
LABEL authors="svemar"
#zadny docker file, proste to tam presun a pust
# scp -r IdeaProjects/softiq/src/* svemar@svemar02.local:/var/www/softiq/
# docker run -d -p 8082:80 --name softiq0.9 -v /var/www/softiq:/usr/local/apache2/htdocs -e APACHE_SERVERNAME=localhost httpd