FROM ubuntu:latest
LABEL authors="svemar"
#zadny docker file, proste to tam presun a pust
# scp -r IdeaProjects/softiq/src/* root@css-sro.cz:/var/www/softiq/
#tenhle podporuje php
# docker run -d -p 8082:80 --name softiq0.9php -v /var/www/softiq:/var/www/html php:apache
# tento je stary
# docker run -d -p 8082:80 --name softiq0.9 -v /var/www/softiq:/usr/local/apache2/htdocs -e APACHE_SERVERNAME=localhost httpd